var imgData = {
    logo:[
        "img/logo/logo.png"
    ],
    part:[
        "img/part/part-1.png",
        "img/part/part-2-1.png",
        "img/part/part-2-2.png",
        "img/part/footer.png"
    ],
    pic:[
        "img/pic/1.png",
        "img/pic/2.png",
        "img/pic/3.png",
        "img/pic/4.png",
        "img/pic/5.png",
        "img/pic/6.png",
        "img/pic/7.png",
        "img/pic/8.png",
        "img/pic/9.png",
        "img/pic/10.png",
        "img/pic/11.png",
        "img/pic/12.png",
        "img/pic/13.png",
        "img/pic/14.png",
        "img/pic/15.png",
        "img/pic/16.png",
        "img/pic/17.png",
        "img/pic/18.png",
        "img/pic/19.png",
        "img/pic/20.png",
        "img/pic/21.png",
        "img/pic/22.png",
        "img/pic/23.png",
        "img/pic/24.png"
    ]
}
